language: shell
dist: focal

env:
  HADOLINT: "${HOME}/hadolint"

install:
  - curl -sL -o "$HADOLINT" "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" && chmod +x "$HADOLINT"

script:
  - shellcheck update.sh
  - shfmt -d -i 2 update.sh
  - $HADOLINT */Dockerfile
  - ./update.sh && git diff --exit-code
